version: '3'
services:
  fastapi-micro-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      # docker build --target development --tag fastapi:dev .
    image:
      fastapi:dev
    command: ["uvicorn", "--host", "0.0.0.0", "--reload", "--log-level", "debug", "main:app"]
      #- uvicorn
      #- --host 0.0.0.0
      #- --reload
      #- --log-level debug
      #- main:app
      # - --port 8000
    ports:
      - "127.0.0.1:8000:8000"

  system-test:
    depends_on:
      - fastapi-micro-service
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    image:
      fastapi-test:dev
    environment:
      FASTAPI_ROOT: "http://fastapi-micro-service:8000"
    # command: ["/bin/sleep", "86400"]
    command: [ "pytest", "-vv", "tests/system"]

  load-test:
    depends_on:
      - fastapi-micro-service
    build:
      context: .
      dockerfile: Dockerfile-k6
    image:
      fastapi-load:dev
    environment:
      FASTAPI_ROOT: "http://fastapi-micro-service:8000"
    # k6 is implicit and only its args need to be supplied.
    command: --verbose run /opt/load/load.js --vus 4 --iterations 1000
    # command: --verbose run /opt/load/load.js --vus 4 --duration 1m
    # command can be overridden:
    #   docker-compose run load-test --verbose run /opt/load/load.js --vus 4 --duration 1m
    # entrypoint: ["/bin/sleep", "86400"]
    # entrypoint can be overridden:
    #   docker-compose run --entrypoint sh load-test
    #   docker-compose run --entrypoint "sleep 86400" load-test
